parameters:
  gaya.htmlcompressor.enabled: true
  gaya.htmlcompressor.class: Gaya\Bundle\HtmlcompressorBundle\Helper\Compressor
  gaya.htmlcompressor.listener.class: Gaya\Bundle\HtmlcompressorBundle\EventListener\CompressorListener
  
services:
  gaya.htmlcompressor:
    class: %gaya.htmlcompressor.class%
    
  gaya.htmlcompressor.listener:
    class: %gaya.htmlcompressor.listener.class%
    arguments: [ @gaya.htmlcompressor, %gaya.htmlcompressor.enabled% ]
    tags: 
       -   { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }